/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertType = { 'out_of_range' : null } |
  { 'drifting' : null } |
  { 'returned' : null };
export interface Device {
  'id' : string,
  'batteryPercent' : bigint,
  'name' : string,
  'rssi' : bigint,
  'isConnected' : boolean,
  'lastSeen' : Time,
}
export interface GeofenceAlert {
  'id' : bigint,
  'alertType' : AlertType,
  'message' : string,
  'deviceId' : string,
  'timestamp' : Time,
  'deviceName' : string,
}
export interface GeofenceSettings {
  'isEnabled' : boolean,
  'deviceId' : string,
  'radiusMeters' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGeofenceAlert' : ActorMethod<
    [string, string, string, AlertType],
    undefined
  >,
  'addOrUpdateDevice' : ActorMethod<[Device], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAlerts' : ActorMethod<[], undefined>,
  'deleteDevice' : ActorMethod<[string], undefined>,
  'getAllDevices' : ActorMethod<[], Array<Device>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDevice' : ActorMethod<[string], [] | [Device]>,
  'getGeofence' : ActorMethod<[string], [] | [GeofenceSettings]>,
  'getRecentAlerts' : ActorMethod<[], Array<GeofenceAlert>>,
  'getScanInterval' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGeofence' : ActorMethod<[GeofenceSettings], undefined>,
  'setScanInterval' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];