/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertType = IDL.Variant({
  'out_of_range' : IDL.Null,
  'drifting' : IDL.Null,
  'returned' : IDL.Null,
});
export const Time = IDL.Int;
export const Device = IDL.Record({
  'id' : IDL.Text,
  'batteryPercent' : IDL.Nat,
  'name' : IDL.Text,
  'rssi' : IDL.Int,
  'isConnected' : IDL.Bool,
  'lastSeen' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GeofenceSettings = IDL.Record({
  'isEnabled' : IDL.Bool,
  'deviceId' : IDL.Text,
  'radiusMeters' : IDL.Nat,
});
export const GeofenceAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : AlertType,
  'message' : IDL.Text,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
  'deviceName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGeofenceAlert' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AlertType],
      [],
      [],
    ),
  'addOrUpdateDevice' : IDL.Func([Device], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAlerts' : IDL.Func([], [], []),
  'deleteDevice' : IDL.Func([IDL.Text], [], []),
  'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevice' : IDL.Func([IDL.Text], [IDL.Opt(Device)], ['query']),
  'getGeofence' : IDL.Func([IDL.Text], [IDL.Opt(GeofenceSettings)], ['query']),
  'getRecentAlerts' : IDL.Func([], [IDL.Vec(GeofenceAlert)], ['query']),
  'getScanInterval' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGeofence' : IDL.Func([GeofenceSettings], [], []),
  'setScanInterval' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertType = IDL.Variant({
    'out_of_range' : IDL.Null,
    'drifting' : IDL.Null,
    'returned' : IDL.Null,
  });
  const Time = IDL.Int;
  const Device = IDL.Record({
    'id' : IDL.Text,
    'batteryPercent' : IDL.Nat,
    'name' : IDL.Text,
    'rssi' : IDL.Int,
    'isConnected' : IDL.Bool,
    'lastSeen' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GeofenceSettings = IDL.Record({
    'isEnabled' : IDL.Bool,
    'deviceId' : IDL.Text,
    'radiusMeters' : IDL.Nat,
  });
  const GeofenceAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : AlertType,
    'message' : IDL.Text,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
    'deviceName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGeofenceAlert' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AlertType],
        [],
        [],
      ),
    'addOrUpdateDevice' : IDL.Func([Device], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAlerts' : IDL.Func([], [], []),
    'deleteDevice' : IDL.Func([IDL.Text], [], []),
    'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevice' : IDL.Func([IDL.Text], [IDL.Opt(Device)], ['query']),
    'getGeofence' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GeofenceSettings)],
        ['query'],
      ),
    'getRecentAlerts' : IDL.Func([], [IDL.Vec(GeofenceAlert)], ['query']),
    'getScanInterval' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGeofence' : IDL.Func([GeofenceSettings], [], []),
    'setScanInterval' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };